version: '3.7'

services:

  db2:
    image: ibmcom/db2:11.5.5.1
    container_name: db2
    ports:
      - target: 50000
        published: 50000
        protocol: tcp
        mode: host
    privileged: true
    environment:
      LICENSE: accept
      ARCHIVE_LOGS: "false"
      AUTOCONFIG: "false"
      DBNAME: jamestst
      DB2INSTANCE: jamestst
      DB2INST1_PASSWORD: james123
    # command: su - db2inst1 -c "db2start; db2 CREATE DATABASE BOOKS"
